name: Run Demo Test
on:
  push:
    branches:  [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run Go Rest Smoke
      run: mvn clean test -DsuiteXmlFile=testng.xml
    - name: Upload Extent HTML report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: go-rest-report
        path: reports/extent/report_*.html
